### PR TITLE
Allow config path to be configurable

### PR DESCRIPTION
**Pull request by bryanspears**
Our current packaging system requires a directory called "config" in the root. Was easier to do this than change the packaging system. Figured I'd contribute the change + a test since it doesn't hurt anything. :smile:

### CODE REVIEW

**Comment by grawk** [comment]
I tried this change locally, along with renaming my config dir to fig:

``` js
app.use(kraken({configdir: path.resolve(__dirname, 'fig')}));
```

I receive the following error:

``` shell
/Users/medelman/.nvm/current/bin/node server.js
Server listening on http://localhost:8000
Unhandled rejection Error: Cannot find module '/Users/medelman/src/krakex/gen-makara-dust-i18n-less/routes'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at index (/Users/medelman/src/krakex/gen-makara-dust-i18n-less/node_modules/express-enrouten/lib/index.js:15:14)
    at EventEmitter.onmount (/Users/medelman/src/krakex/gen-makara-dust-i18n-less/node_modules/express-enrouten/index.js:55:13)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/Users/medelman/src/krakex/gen-makara-dust-i18n-less/node_modules/express/lib/application.js:237:8)
    at Array.forEach (native)
    at EventEmitter.use (/Users/medelman/src/krakex/gen-makara-dust-i18n-less/node_modules/express/lib/application.js:216:7)
    at register (/Users/medelman/src/krakex/gen-makara-dust-i18n-less/node_modules/meddleware/index.js:220:24)
    at Array.forEach (native)
    at EventEmitter.onmount (/Users/medelman/src/krakex/gen-makara-dust-i18n-less/node_modules/meddleware/index.js:199:14)
    at EventEmitter.g (events.js:260:16)

```

It's the same error you might see if you simply rename or delete the default config directory.

**Comment by tomalex0** [comment]
@grawk  Like to know if this is going to part of kraken framework soon?

**Comment by tomalex0** [comment]
I have one more request specific to my use case, im trying to create sub application  like 
https://github.com/jasisk/middleware-patterns#subapp-pattern and would like to point all sub applications config to one folder .

More like an option  for `baseconfigdir` or so.

**Comment by grawk** [comment]
My bad... user error. I tried to path in a fully resolved path in the `config` property. Oops. The change looks fine to me. Would be interested if any of the more deeply involved committers can see any possible drawbacks to this change? 👍 as far as I'm concerned.

**Comment by grawk** [comment]
would resolve #350

**Comment by bryanspears** [comment]
Not hearing any more suggestions? We've been maintaining our own fork of kraken for months just to have this capability. :-)

**Comment by grawk** [comment]
I'm ready to merge this. Gonna find some more reviewers and knock this out. @bryanspears

**Review by shaunwarman — APPROVED** [review]

**Comment by grawk** [comment]
@bryanspears want to doc this?

**Comment by bryanspears** [comment]
Looks like this was merged but never released? Just tried 2.1.0 via npm and this change is not present. Looks like nothing has changed on npm for kraken-js in two years?

What is paypal using these days? :smile:

**Comment by gabrielcsapo** [comment]
@bryanspears we are still using kraken! If it’s a testament to the operability of kraken it is that it hasn’t had to change in two years 😊

**Comment by tomalex0** [comment]
Just checking if this change will be released soon  :) ?

**Comment by gabrielcsapo** [comment]
finally published https://github.com/krakenjs/kraken-js/releases/tag/2.2.0

**Pull request merged**
