### PR TITLE
Added kraken logo into README.md

### PR DESCRIPTION
**Pull request by Knighton910**
:+1: I hope you like what i did to the README.md

### CODE REVIEW

**Comment by jasisk** [comment]
Hey kel. Thanks for the PR.

I like the idea of the logo in the readme but would prefer if it was left-aligned and using the markdown syntax:

```
![kraken-js](public/krakenLogo.png "kraken-js - Give your node.js express apps some extra arm")
```

If you can make that change, I'll merge it in.

**Comment by Knighton910** [comment]
Sweet! will do

**Comment by Knighton910** [comment]
I'm reading an article right now, as soon as i'm done, I'll make that change. :100:

**Comment by Knighton910** [comment]
I sure you're a busy guy, I just wanted to know if my last commit was up to your standards.

**Comment by jasisk** [comment]
Hey Kel.

No worries. Was hoping you could switch from HTML to the markdown syntax mentioned in my last comment?
Will merge as soon as you can! :grinning:

**Comment by Knighton910** [comment]
ah. Sorry about that, will do.

**Comment by Knighton910** [comment]
sweet I think you'll like it now. :100:

**Comment by Knighton910** [comment]
Can i get that sweet merge :+1: :sparkles: :jack_o_lantern: please? lol

**Comment by jasisk** [comment]
Yup. :+1:

**Comment by Knighton910** [comment]
haha :smile: Awesome! Thanks dude.

**Pull request merged**
