### PR TITLE
Remove bluebird, use polyfill for node <8 util.promisify. 

### LINKED ISSUE #494: remove bluebird 🔥
With native promise support we can easily move away from bluebird to get a nice performance boost for install and promisify functionality. 

[1] https://nodejs.org/api/util.html#util_util_promisify_original

### PR DESCRIPTION
**Pull request by osukaa**
Closes krakenjs/kraken-js#494

### CODE REVIEW

**Comment by shaunwarman** [comment]
👍 - thoughts @aheckmann ?

**Comment by xjamundx** [comment]
This is fully b/w compat. Right? Ideally i'd love to see a special kraken node8 release with better support for async middleware and maybe some other changes, but....this is great

**Comment by osukaa** [comment]
@xjamundx Yes, this is fully b/w compatible, all the tests (you can check travis) are running in 4, 6 and 8.

**Comment by aheckmann** [comment]
I'm good with this change since it doesn't look like promises are used for
anything other than startup related actions.

**Comment by aheckmann** [comment]
> Ideally i'd love to see a special kraken node8 release with better support for async middleware and maybe some other changes

Why not use a different project like hapi or koa which already has this support?

**Comment by grawk** [comment]
Going through old PRs. Since we are now at node@10 and above, we can use the built in `util` module and no longer need to require `util.promisify`. @osukaa do you have any time/interest in refactoring this PR? Or shall we close it and have the team open a new PR?

**Comment by osukaa** [comment]
Sure! let me update the branch

**Comment by osukaa** [comment]
@grawk I updated the branch, and removed the polyfill :D

**Pull request closed without merging**
