### PR TITLE
Removing unnecesary Bluebird import

### PR DESCRIPTION
**Pull request by thefourtheye**

### CODE REVIEW

**Comment by aredridel** [comment]
Seems reasonable. Mixes in a style change too, but a trivial one.

**Comment by jasisk** [comment]
:+1:

**Comment by thefourtheye** [comment]
@jasisk @aredridel  Shall I submit another PR for v2.x branch?

**Comment by aredridel** [comment]
Good question. We need to catch the 2.x branch up with 1.x en masse, probably.

**Comment by thefourtheye** [comment]
@aredridel Here it is https://github.com/krakenjs/kraken-js/pull/357

**Pull request merged**
