### PR TITLE
Adding a section about reading configs in your kraken-app

### PR DESCRIPTION
**Pull request by pvenkatakrishnan**
for https://github.com/krakenjs/kraken-js/issues/299

### CODE REVIEW

**Comment by aredridel** [comment]
:+1: and I'd :+1:  again if I could.

**Comment by lmarkus** [comment]
:fireworks:

**Comment by totherik** [comment]
I like it except for the invalid identifier in the code examples (lines 484 and 493): `var config-value`. The `-` token isn't allowed in that position so the JS is invalid.

**Comment by pvenkatakrishnan** [comment]
updated

**Pull request merged**
