### PR TITLE
Fix additional deprecation warnings regarding res.send

### PR DESCRIPTION
**Pull request by totherik**
Server startup middleware and some tests need updating.

### CODE REVIEW

**Comment by totherik** [comment]
lol, Promises. Fixing the build...

**Comment by aredridel** [comment]
Aw. The redef-of-Promise just makes me sad.

**Comment by aredridel** [comment]
LGTM though.

**Comment by totherik** [comment]
Lol, even more sad because it's [just a jshint thing](https://github.com/jshint/jshint/issues/1747). It's not available in Node so using the global isn't possible. Guess it future-proofs our code...

**Comment by aredridel** [comment]
Heh, yeah, future-proofs against a non-error. You can always override globals in a module. It's a new scope!

**Comment by totherik** [comment]
Lol, well yeah, it's called a "hint" for a reason. :grinning: I'm cool with knowing when I'm inadvertently shadowing globals in any context though. Being explicit helps other readers know my intent.

**Comment by pvenkatakrishnan** [comment]
looks good to me.

**Pull request merged**
