### PR TITLE
added support where country/region code = "C2"

### PR DESCRIPTION
**Pull request by ghost**
CHANGELOG:
1.  added support where country/region code = "C2"

### CODE REVIEW

**Comment by lmarkus** [comment]
See this PR (https://github.com/krakenjs/kraken-js/pull/306) for a discussion relevant to this one.

The big question: Is it feasible for you to upgrade to Kraken 1.x instead?

Small comment: As good practice, this needs a unit test.

**Comment by aredridel** [comment]
Hm, I'm +1 on this, I think.

**Comment by totherik** [comment]
Yeah, I'm :+1: the change but would like to see a test case, too.

**Comment by ghost** [comment]
Hi, 
I added the test case to this pull request
FYI: the following server is down at the moment: https://travis-ci.org/

**Comment by aredridel** [comment]
Yeah, down due to DNSSimple DDoS.

**Comment by ghost** [comment]
the CI build passed for my compiler.js test addition.  
please let me know if you have any questions.

**Comment by ghost** [comment]
Thanks for merging this pull request.
Will there be an associated tag created?

**Comment by aredridel** [comment]
Yeah, we'll have to get a release out.

**Pull request merged**
