### PR TITLE
Listen on a random, rather than specific port

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by jasisk** [comment]
:+1: pending travis
Maybe throw a comment in there linking to ephemeral port docs for the less familiar reading our tests?

**Comment by pvenkatakrishnan** [comment]
:+1:

**Comment by aredridel** [comment]
Do you know of an easily linkable doc?

**Comment by sixlettervariables** [comment]
Worth a comment somewhere about the change (e.g. my Fortune 5 IT dept blocks apps using specific port ranges indiscriminately, makes for bizarre error conditions when tests randomly fail).

**Comment by aredridel** [comment]
Oh, wow. Blocks them on localhost?! That's wacky!

**Comment by jasisk** [comment]
@sixlettervariables that's the first of heard of this. How often do you this this problem crop up in opensource for you? We use supertest all. over. the. place. I bet a number of other projects do, too. Even projects that promote not listening for server tests (e.g., hapi thanks to shot) still occasionally have to listen, and nearly all—in my experience—are using an ephemeral port.

**Comment by sixlettervariables** [comment]
Supertest is exactly where I found this fun tidbit out while trying to contribute back to a few repos. I've simply written fixes for the test suites to pull a pseudo-random (sans "invalid" port numbers).

**Comment by aredridel** [comment]
Aye. Do you retry on port in use? That sounds like it would complicate a lot. Letting the kernel pick gets you a guaranteed free port.

**Comment by sixlettervariables** [comment]
Believe me that is just a hack to make it work in my environment and I never attempt to push those test harness updates to remotes.

**Comment by aredridel** [comment]
Ah, cool. What a wacky environment!

**Comment by jasisk** [comment]
Yeah, that's wonky. Well, thanks for the insight. :+1:

**Pull request merged**
