### PR TITLE
Plugin architecture for middleware

### PR DESCRIPTION
**Pull request by AlbertoGP**
Similar to the existing `requestStart`, `requestBeforeRoute`, etc.
give the application a chance to disable/replace
each middleware that Kraken uses by implementing
`reviewMiddleware(slots)`

For instance, to remove the favicon middleware
put this in the application's index.js:

```
app.reviewMiddleware = function reviewMiddleware(middleware) {
    delete middleware.favicon;
};
```

This covers my use case in a more general way
than #47 ("Configurable favicon in config/middleware.json")
and also covers #41 ("add config session able or disable")
so I propose it as a fix for #50 ("Plugin Architecture for Middleware").

### CODE REVIEW

**Comment by lmarkus** [comment]
I need to look at it in more detail, and will do so on Monday.
In the meantime, this PR fails to build. [See details](https://travis-ci.org/paypal/kraken-js/builds/15090707)

Can you fix this before we start the review? (Working from a mobile, so I haven't even seen what it is).

**Comment by AlbertoGP** [comment]
Sure, it was a missing space after the function keyword in an anonymous function.
It's fixed now.

**Comment by totherik** [comment]
Interesting solution. I was thinking we'd go more toward a configuration-based approach, possibly providing an alternative to the delegate methods as part of this change.

**Comment by AlbertoGP** [comment]
I've kept the changes at a minimum for now. It would be easy to develop it further.
I suppose that the delegate methods you are talking about are `app.requestStart()` etc. They would be additional slots. That way in `lib/appcore.js#proto._middleware()`, instead of `app.use(...)` for each slot, all of them would be appended with a loop.
What I have in mind is, instead of the slots object, a `middleware` object with two fields: `chain` and `slots`.
`middleware.chain` is an array of slot names `['favicon', 'compiler', ..., 'errorHandler']` and `middleware.slots` is the slots object.
The `reviewMiddleware()` function would receive that `middleware` object, so you can alter the chain in any way you want and define your own slots. Simple things like removing some slots would still be simple, for instance:

```
app.reviewMiddleware = function reviewMiddleware(middleware) {
    delete middleware.slots.favicon;
    delete middleware.slots.session;
};
```

If we want that in the configuration file, we just need to use strings for the slot values.
For instance, the default favicon slot would be `{ "favicon":"favicon" }` and I could replace it with my own by writing `{ "favicon": "app.favicon" }` to use a function I define in my `index.js`.
In this approach, we would remove the favicon and session middlewares by having this in `config/middleware.json`:

```
{
    "middleware": {
        "slots": { "favicon": false, "session": false },
        "session": {
            ...
        }
    }
}
```

That is, the values from `middleware.json` would extend the `slots` object, not replace it.
As the `chain` field would be replaced completely if specified (we could zip the arrays together or something, but I think that'd get too messy), I would prefer to do any modifications to it in the `reviewMiddleware()` function so that I don't need to keep updating it any time you modify the default chain: I want Kraken to handle all those details like which middleware should run before which other and, in general, run by default any middleware that you consider useful as Kraken evolves.

**Comment by AlbertoGP** [comment]
I've rebased the branch on the current master to incorporate the changes in the meantime. Is this right, or should I have done a merge instead?

Anyhow, now the build fails because `_middleware()` has too many statements.
I'll take the slot object declaration/initialization out of the function. The reason for keeping it there is to keep it close to the `app.use()` statements because with the current implementation they must be kept in synch manually.
If I implement the changes I described in https://github.com/paypal/kraken-js/pull/53#issuecomment-30123769 it would not be a problem any more.

Is this pull request something you'd consider merging, or do you have a different approach in mind?
What about the proposed developments in https://github.com/paypal/kraken-js/pull/53#issuecomment-30123769 ?
Should I implement that in another branch and issue a separate pull request?

**Comment by lmarkus** [comment]
Hi @AlbertoGP , thanks for the contribution.

The core team has been working on a flexible solution for loading middleware in any order, based on an external configuration. (Coming soon!)  

While there are some similarities to this solution, the final proposal looks quite different.
I'm going to reject this Pull Request, but please follow #50 so you can see what this proposal will be.

**Pull request closed without merging**
