### PR TITLE
updates depends

### PR DESCRIPTION
**Pull request by gabrielcsapo**
- adds node versions to test in travis.yml
- updates the travis script to run lint as well
- adds jshint ignore line to shutdown.js

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@tlivings @grawk @shaunwarman thoughts?

**Comment by grawk** [comment]
No issues in general. We'd want to make sure we have a fairly comprehensive test internally before releasing something that gets picked up automatically within PayPal.

**Comment by gabrielcsapo** [comment]
@grawk thoughts on having Milind test this?

**Comment by grawk** [comment]
i don't see a problem with merging and cutting an `rc` branch

**Comment by grawk** [comment]
:+1:

**Pull request merged**
