### PR TITLE
Bumping lusca version

### PR DESCRIPTION
**Pull request by pvenkatakrishnan**

### CODE REVIEW

**Comment by lmarkus** [comment]
Travis fail! :(

**Comment by pvenkatakrishnan** [comment]
yep express is not getting installed even though there is a peer dependency in kraken. Weird.

**Comment by jeffharrell** [comment]
Does this build locally on a fresh copy?

**Comment by pvenkatakrishnan** [comment]
nope it does not. Looks like peer dependency is not sufficient

**Comment by jeffharrell** [comment]
Ah, if you're `npm install`ing it directly it needs to have it as a devDependency as well. 

I fixed this and Lusca (along with a few other things) over in https://github.com/paypal/kraken-js/commit/298867e2d36637aa253dc2b6e9200f05c979ebe4 on the .next branch, so we can probably close this and focus on that branch.

**Pull request closed without merging**
