### PR TITLE
Refactoring kraken init options.

### PR DESCRIPTION
**Pull request by ghost**
This pull request refactors kraken init options into a function of it's own.

### CODE REVIEW

**Comment by shaunwarman** [comment]
👍 but I say we fix linter issue from #450 and remove the jshint ignore here

**Comment by grawk** [comment]
I'm not clear on the benefit of pulling this up into its own function. I don't anticipate needing to reuse it anywhere else.

**Comment by jasisk** [comment]
> I'm not clear on the benefit of pulling this up into its own function. I don't anticipate needing to reuse it anywhere else.

Seconded.

**Comment by grawk** [comment]
@IAmAnubhavSaini if you want to open another PR that's specifically related to linting errors/warnings, please do so. I'm going to close this PR though as there is no apparent value in moving the init option setup to another function.

**Pull request closed without merging**
