### PR TITLE
update lusca dependency to 1.5.1

### PR DESCRIPTION
**Pull request by codyleyhan**
- Updated lusca to the newest version to allow for added features
- Updated gitignore for npm v5

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
👍

**Review by gabrielcsapo — APPROVED** [review]

**Comment by Greg-Wilburn** [comment]
👍

**Review by Greg-Wilburn — APPROVED** [review]

**Comment by gabrielcsapo** [comment]
thank you @codyleyhan will comment back with the version this gets published under.

**Comment by gabrielcsapo** [comment]
published in https://github.com/krakenjs/kraken-js/releases/tag/2.2.0

**Pull request merged**
