### PR TITLE
Update appcore.js

### PR DESCRIPTION
**Pull request by tomalex0**
Add config option to enable/disable gzip compression.
By default compression is disabled.

### CODE REVIEW

**Comment by jasisk** [comment]
This is precisely one of the reasons we moved to priority-driven configuration in kraken 1.0—it became clear that not having absolutely control over middleware registration order was a problem. So I certainly don't disagree with the problem. That said ...

`v0.7` has been superseded by `v1.x`—is there any reason in particular that you're sticking with `v0.7`?

**Comment by tomalex0** [comment]
I'm still using 0.7.5 version, is there any workaround to apply gzip without changing core file?

I'm still sticking because we went ahead with lot of development in 0.7.x and  not sure when we will be migrating to 1.x version.

**Comment by totherik** [comment]
I'm not opposed to this change although it seems to differ slightly from the [only other similar implementation](https://github.com/tomalex0/kraken-js/blob/1218aaa878bb0291d962d79b6244d60af57e94da/lib/appcore.js#L185-L187) in the existing code.

**Comment by totherik** [comment]
@tomalex0, could this be updated to match the existing pattern?

**Comment by tomalex0** [comment]
Sure

**Comment by tomalex0** [comment]
@totherik  Not sure, what went wrong after i edited the files again?  Is everything fine after the recent pull request?

**Comment by totherik** [comment]
Sorry @tomalex0, I wasn't totally clear in my request.

The only existing example of what you're trying to accomplish is the optional [multipart](https://github.com/krakenjs/kraken-js/blob/447636c9cf08179f08f1b4129da344ff6b3b7104/lib/appcore.js#L179-L181) configuration. 

``` javascript
if (config.multipart) {
    app.use(kraken.multipart(config.multipart.params));
}
```

Note that the configuration options are not namespaced under `config.express`, but instead, just directly under config:

``` javascript
if (config.compress) {
    app.use(express.compress(config.compress));
}
```

Also, it appears that the implementation, `compression`, [accepts options](https://github.com/expressjs/compression/blob/c45fae318f6853667bc588386cc78692eaf1f7ac/index.js#L54), so as in the example above, the options should act as both the flag and the configuration for the middleware.

Finally, just for recordkeeping, this is _not_ backward compatible and will require a 0.8 release.

-Erik

**Comment by totherik** [comment]
Le sigh. Not-compatible wouldn't mean 0.8, it would mean something else completely. Looking for suggestions from the team as to whether to allow this as a minor release or just bump the patch release.

**Comment by lmarkus** [comment]
@totherik: How do you mean non backwards compatible? This shouldn't break existing 0.7.x apps (Unless I'm misunderstanding what you meant).

Once the code review is finalized, my vote would be for 0.8.0 minor bump.
Rationale: New feature is being added without changing the overall behavior of the app.

**Comment by totherik** [comment]
I mean it's not backward compatible because we cannot push this code and expect that all current 0.7 applications will work without issue. The definition is not constrained to "changing the overall behavior of the app."

In this case there could be applications with a config key called "compress". If we push this code applications will get it via "~0.7.x" in their package.json. If any application happens to have a config key named "compress" their app will now behave differently. That change in behavior is not backward compatible.

**Comment by lmarkus** [comment]
Thanks for the clarification. I see what you meant. 
Le sigh indeed.

**Comment by lmarkus** [comment]
A few more thoughts on this.
I've gone back to Semver a couple of times, and keep looking at this part:
`Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.`

I also read this over:
https://github.com/npm/node-semver#caret-ranges-123-025-004
`~0.7` users won't be affected because it will only move through patch versions, and `^0.7` users won't be affected either, given the safety mechanism of caret for pre-release software:

```
^0.2.3 := >=0.2.3 <0.3.0
^0.0.3 := >=0.0.3 <0.0.4 
```

Based on this , I still think that a 0.8 release should be safe, as you'd have to manually upgrade to it.
This would affect what is likely a small group (people who will consciously upgrade AND who are currently using `compress` as a key in their config.).

(Of course, that is if you guys decide it's worthwhile to accept the PR to enable compress for what is also going  to be a small set of legacy users)

**Comment by aredridel** [comment]
Yeah. The semver spec says "Eh, whatever". NPM had to tighten that up and use it like the major shifted one position when major = 0, because that's what the community practice roughly shaped up to be. It broke too much to treat all 0.x versions as not equal to each other, which is the smart way to interpret the spec.

**Comment by totherik** [comment]
What _will_ be affected is that we support `current` - 1, meaning `1.x` and `0.7.x`. That means if we roll out `0.8.x` we either drop support for everyone on `0.7.x` or we start supporting a 3rd version.

**Comment by aredridel** [comment]
How complex is the upgrade path?

**Comment by totherik** [comment]
Well, save this breaking change, the proposed `0.8.x` and `0.7.x` are effectively the same.

**Comment by aredridel** [comment]
If it defaults to off, it'd be backward compatible, yes?

**Comment by totherik** [comment]
No. If any application happens to have a config property named `compress` it would unknowingly (to the app owner) enable this feature.

**Comment by aredridel** [comment]
Ah, yeah. Since we don't have a good namespace for it. Is there a namespace that could be chosen that would be backward compatible?

**Comment by totherik** [comment]
Unfortunately, not that I'm aware of. My proposed [update](https://github.com/krakenjs/kraken-js/pull/306#issuecomment-64253932) correctly (e.g. matches existing style) namespaces under `middleware`, but other than that, nope.

**Comment by aredridel** [comment]
Could use implausible namespace rather than provably separate. Could even be something ugly like `config['kraken-0.7'].compress`.

**Comment by lmarkus** [comment]
:grin:

**Comment by aredridel** [comment]
Hey, backward compatibility is a pain. But a worthwhile pain. Perhaps there's a humane middle ground.

**Comment by aredridel** [comment]
(I deliberately chose something toward the 'inhumane but if you argue that it's backward incompatible you're just being silly' end of the spectrum.)

**Comment by totherik** [comment]
@lmarkus that's not terribly helpful. do you have any more thoughts/proposals on how to make this work? Also, I would like to hear back from @tomalex0 to see if he's still interested in seeing this PR through.

**Comment by lmarkus** [comment]
I do. Composing a more complete response now,

**Comment by lmarkus** [comment]
So the kludge is just a graphical representation of what we _don't_ want to end up doing (Plus a little humor for Monday) . Just taking a step back for a moment and looking at the overall situation. I think we're taking things to their logical extremes here.

As @totherik mentioned, there's the danger of ending up in a jQuery-like situation, where you have to end up supporting multiple versions.

One of the reasons for all the work that went into 1.0 was to offer the flexibility to avoid situations like this one. One option is to say that this PR won't be accepted, as it will increase the maintenance overhead on a small team. It's particularly painful for me, as I spent time evangelizing the framework, and helping build up the community.  @totherik , @aredridel , I don't have insight into this, but is the support required for 0.7.x today significant enough to make the concern for 0.8.x valid? 

@tomalex0, @totherik is it feasible to use the `requestBeforeRoute` hook to enable compression for the routes, and other middleware added after that?.  This would be my preferred solution to this issue.

If not feasible, the proposal from @aredridel is not pretty, but is certainly effective.

Finally, since  0.7.x has been out for well over a year and there haven't been any requests for this, I think it can be considered a one-off. I'd be happy to look into implementing a monkey-patch for this.

**Comment by aredridel** [comment]
Also: this build is failing.

**Comment by tomalex0** [comment]
@lmarkus  if i remember i have tried `requestBeforeRoute`   and css and js was not compressed only html did.

**Comment by tomalex0** [comment]
Just an update, i'm migrating to kraken1.0 version. So i'm fine even if you don't update  previous version

i think in 1.0 version, below config options is good enough?

```
"compress" : {
            "enabled": true,
            "priority": 10,
            "module" : "compression"
        },
```

**Comment by aredridel** [comment]
Sure should be. That's super early!

**Pull request closed without merging**
