### PR TITLE
Prevent Double Close.

### PR DESCRIPTION
**Pull request by jasisk**
Addresses #402 and #388.

### CODE REVIEW

**Comment by grawk** [comment]
:+1:

**Comment by tlivings** [comment]
Oops, merge signified :+1:

**Comment by pvenkatakrishnan** [comment]
:+1:

**Comment by pvenkatakrishnan** [comment]
ups already merged. But never mind.

**Comment by tlivings** [comment]
Is there a PR for 2.x as well?

**Comment by jasisk** [comment]
~~Opening.~~

#419

**Pull request merged**
