### PR TITLE
Adding logging the stack trace in case of a 500 error.

### PR DESCRIPTION
**Pull request by pvenkatakrishnan**
It seems like this will be helpful to dump on the console. Thoughts ?

### CODE REVIEW

**Comment by grawk** [comment]
So this would only show up if i set `NODE_DEBUG=kraken/middleware/500` ?

And yeah, definitely useful..

**Comment by pvenkatakrishnan** [comment]
I am more than happy to just `console` it

**Comment by totherik** [comment]
I'd prefer not to `console`, but we'll just need to surface debuglog configuration documentation better to support this change. :+1: would like to get @jasisk opinion since he's the maintainer.

**Comment by grawk** [comment]
Should be shown conditionally.. via NODE_DEBUG or other flag IMO. Also, in the krakenjs.com reboot plan, I'm making allowance for documenting all our default middleware. It can definitely be doc'd there.

**Comment by pvenkatakrishnan** [comment]
:+1: @grawk

**Comment by jasisk** [comment]
Agreed that we shouldn't just dump to the console and much prefer debuglog. :+1:

**Comment by lmarkus** [comment]
:+1: Debug all the things!
These have been really useful in other modules like meddleware when troubleshooting stuff.

That said, are you guys planning on baking in some smarter logging into the framework at some point (Something like Winston, or similar)?

**Comment by jasisk** [comment]
Are you aware of [pine](https://github.com/krakenjs/pine)?

**Comment by lmarkus** [comment]
Allrighty then. So the next question is, why not use pine here?

**Comment by pvenkatakrishnan** [comment]
@lmarkus We could definitely write an example app to demonstrate how it can be used alongside kraken. But unsure if it makes sense to prescribe a logging module within kraken (just like it doesn't attach to specific db's or templating engines and gives the flexibility to use any). kraken is meant to be as thin and simple as possible.

**Comment by lmarkus** [comment]
As far as this PR goes, I'm +1.

My arguments is probably something more long-term ( Kraken 2.0? :) ). I argue in favor of something like pine, because it can be kept simple (by default, log to console when run under debug mode). 

Code-wise, it takes the same number of lines: Require the package, insert `log.debug` statements as needed; but it gives you the ability to do more by simply tweaking the config a bit.

**Comment by totherik** [comment]
Baking a logging implementation directly into modules is not the correct solution. Not only does it enforce an unnecessarily strict cross-cutting concern, it creates configuration complexity and assumptions that shouldn't be forced on consumers. Why would someone using vanilla express who want to use `meddleware` alone be forced into a particular logging mechanism just because `meddleware` also happens to be a part of kraken? Suddenly we've created interop and more complex versioning problems for people who choose to use our code. That's a non-starter for me.

**Comment by pvenkatakrishnan** [comment]
Let me add some documentation as well for this. (i mean the debuglog)

**Comment by lmarkus** [comment]
Good point @totherik. It's easy to forget thinking about Kraken as a collection of independent modules.
Thanks.

**Comment by jasisk** [comment]
Sorry for the delay in response. Kind of a strange day.

Anyway, as Erik mentioned, application level logging should be the responsibility of the application, not the framework though I'm all for adding a solution to the generator output (since we've discovered that what we do there ends up sort of being the bible—something we won't be taking as lightly in the future).

Frankly, I'm revisiting the middleware we ship with as unnecessary and downright confusing. Too many assumptions (res.render assumes a rendering engine has been registered, for example) and has nothing to do with the core. Introduces more problems than it solves.

I think the appropriate solution is spend more time making the generator output something more sensible, and document, document, document.

**Pull request merged**
