### PR TITLE
Emitting express events for error handling

### PR DESCRIPTION
**Pull request by pvenkatakrishnan**
First pass for using express events to emit error events to the app.
Tested it against a sample kraken app and verified it works

Fix for https://github.com/paypal/kraken-js/issues/13

### CODE REVIEW

**Comment by pvenkatakrishnan** [comment]
In my apps index.js, tested as:

``` javascript
    server.get('/serverErrorExample', function(req, res, next) {
        next(500);
    });

    server.on('event:fileNotFound', function(req, res, data) {
        //do your thing

    });

    server.on('event:serverError', function(req, res, data) {
        //do your thing
    });
```

**Comment by pvenkatakrishnan** [comment]
ok i got to think of how to change the tests; it is now failing the build as it expects to render a template on these errors which is what we are trying to move away from and give the app more control.

**Comment by totherik** [comment]
Just a few thoughts:
- We already provide a default implementation which renders a response. Shouldn't we keep that for compatibility/flexibility?
- The file `lib/util/errorUtil.js` is unused.
- Prefixing emitted events with `event:` seems redundant. Would it be more flexibly to merely emit `error` events with event args that contain details such as url, actual `Error` response code, etc?

I think we need to identify whether this solution is intended for 1) notification of errors for things such as logging or 2) provide an alternate pattern for _handling_ errors (e.g. rendering), but probably not both.

**Comment by pvenkatakrishnan** [comment]
yaay i fixed the tests! That was a good learning exercise.

**Comment by pvenkatakrishnan** [comment]
@totherik just seeing your comments. 
Interesting. I thought that the idea was not to let the framework do the rendering. Let the app do whatever it wants. Maybe I understood it wrong. 
So the thought is : framework continue doing the rendering BUT notify the app anyway incase it needs to handle it ?

**Comment by pvenkatakrishnan** [comment]
ok changed per suggestions.

**Comment by jeffharrell** [comment]
Just to elaborate on @totherik's comment, the error page rendering should be handled as it currently is via config, but instead of console logging we should be emitting an event. 

There's actually a reference to the app hanging off of `req.app` which should simplify this. You should be able to modify the original code to execute `req.app.emit` when the `fileNoutFound`/`serverError` function first runs.

**Comment by pvenkatakrishnan** [comment]
Also @jeffharrell i removed emitting events from fileNotFound as it was originally not logging console.errors
Only the serverError ones were. let me know if you still think we need them. It is a quick one line change.

**Comment by totherik** [comment]
We will need to ensure errors get propagated to mounted `express` apps. For (contrived) example:

``` javacript
var express = require('express');

var child, parent;

child = express();
parent = express();
app.use(child);

child.emit('error', new Error('where does this go?');
```

EDIT: The reason this might be useful is the new API for `express-enrouten` transparently creates a child express app, so if that child emits an error it would be nice if that was communicated to the parent as people will be attaching listeners to the parent.

**Comment by pvenkatakrishnan** [comment]
Ok will look into this and the test.

**Pull request closed without merging**
