### PR TITLE
update copyright year

### PR DESCRIPTION
**Pull request by PatrickJS**

### CODE REVIEW

**Comment by totherik** [comment]
Awesome, thanks for opening this @gdi2290. Looks like there are a few more places that could be updated, though (assuming I caught them all).

``` bash
$ grep -R --include=*.{js,md,txt} --exclude-dir=node_modules "(C) 2013" .
./Gruntfile.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./index.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/appcore.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/middleware/compiler.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/middleware/error.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/middleware/index.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/middleware/logger.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/middleware/multipart.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/middleware/session.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/middleware/shutdown.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/patch/config.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/patch/index.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/patch/stream.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/util/configutil.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/util/index.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./lib/util/pathutil.js:│  Copyright (C) 2013 eBay Software Foundation                                │
./LICENSE.txt:│  Copyright (C) 2013 eBay Software Foundation                                │
```

**Comment by PatrickJS** [comment]
@totherik .done()

**Comment by totherik** [comment]
good by me :+1:

**Comment by lmarkus** [comment]
Thanks!
Hey, would it be abusing the community if I ~~ask~~ beg you to go through the other modules from krakenjs.com? :grin: 
:angel:

**Comment by alexsantos** [comment]
Done some already :-)

**Comment by alexsantos** [comment]
Just a simple command line:

``` bash
$ grep -Rl --include=*.{js,txt,md} --exclude-dir=node_modules "(C) 2013" . | xargs sed -i 's/(C) 2013/(C) 2014/g'
```

**Pull request merged**
