### PR TITLE
Fix for issue https://github.com/paypal/kraken-js/issues/5

### PR DESCRIPTION
**Pull request by pvenkatakrishnan**
Adding the file name while throwing json config errors.Tested on a sample app.

### CODE REVIEW

**Comment by jeffharrell** [comment]
One minor tweak would be to remove the colon from the output so that it's:

`[Error: SyntaxError: Unexpected token } at  /Users/pvenkatakrishnan/Documents/workspace/IamLegend/config/app.json]`

Otherwise, I'm good with the change.

**Comment by pvenkatakrishnan** [comment]
on second thoughts i was wondering if the line

``` javascript
contents = this._resolver.resolve(contents);
```

also need to go into the try block.... do you see it throwing any kind of errors ? i was only able to get it to err on parsing...

**Comment by totherik** [comment]
this looks good to me. :+1:

**Comment by pvenkatakrishnan** [comment]
Can someone merge this in please ? Looks like we have it reviewed.

**Pull request merged**
