### PR TITLE
Adding error handler middleware

### PR DESCRIPTION
**Pull request by jeffharrell**
Note that these are not hooked up by default in the config, but will be as part of the generator.

Also, updating the package name as an added bonus :+1:

### CODE REVIEW

**Comment by totherik** [comment]
Looks good to me. :+1:

**Comment by jasisk** [comment]
Does it make sense to have generic 4xx and 5xx level handlers instead? Expected vs. unexpected?

**Comment by jeffharrell** [comment]
More generic than this? These just render a page / JSON.

They'll be wired up by the generator when it scaffolds out an app.

-- Jeff

On Mar 18, 2014, at 8:35 AM, "Jean-Charles Sisk" <notifications@github.com<mailto:notifications@github.com>> wrote:

Does it make sense to have generic 4xx and 5xx level handlers instead? Expected vs. unexpected?

**Comment by jasisk** [comment]
I guess I mean not hardcoding 404/500?

**Comment by jeffharrell** [comment]
Wouldn't generalizing them water each down? 

404 is pretty specific. I'd think it the same with 500 where there's an error that was caught. Other 40x/50x status codes I would expect to be returned directly by the app and not randomly occur.

**Comment by jasisk** [comment]
Let me reframe a bit.

I can see someone wanting their 404s working consistently whether or not it was programmatically trigger or just fell through. Same with 50xs. My real suggestion is separately exposing the 4xx/5xx handler implementations from their middleware, such that I could call them on my own.

**Comment by jasisk** [comment]
Meh. I've been sick the last couple of days. Disregard most things I've said / done.

**Comment by jeffharrell** [comment]
Ha, so yea or nay? If nay, I may just be being dense, but provide some code samples to illustrate what you mean :smile:

**Comment by jasisk** [comment]
Yay.
But what I was talking about was something like this based on your 500 handler. Note that it's 7pm on Friday and this is straight comment typing so not exactly well thought out:

``` JavaScript
module.exports = function (template) {
    function generator(code, model) {
        return function middleware(req, res, next) {
            if (req.xhr) {
                res.send(code, model);
            } else {
                res.status(code);
                res.render(template, model);
            }
        };
    }

    function serverError(err, req, res, next) {
        var model = { url: req.url, err: err };
        generator(500, model)(req, res, next);
    }

    serverError.generator = generator;

    return serverError;
};
```

**Comment by jasisk** [comment]
My brain has been broken all week. Le sigh.

Marging.
:boom:

**Pull request merged**
