### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by airtonix**
briefly talk about the sass support

### CODE REVIEW

**Comment by jasisk** [comment]
Hi @airtonix,

By default, the sass compiler isn't registered (and it doesn't have a default path of css).

In order to use it, you must register it (by including it in your `middleware:compiler` list), and effectively unregister the less compiler (preferably, by setting `less` to `false`).

Here's an example `middleware-development.json` snippet:

``` json
{
  "middleware": {
    "compiler": {
      "sass": "css",
      "less": false
    }
  }
}
```

**Comment by totherik** [comment]
Also, I (personally) consider [defaulting to `less` a bug](https://github.com/paypal/kraken-js/issues/6).

**Comment by jasisk** [comment]
No argument there. Sincerely, the guy that uses `sass`.

**Comment by airtonix** [comment]
@jasisk @totherik Forgive my noob question here, but I'm normally familiar with my sass compiling occurring in grunt tasks (sailsjs), or in a management command (django), or failing that in another terminal window with `compass watch`.

While I did make this pull request in order to bring attention (for a wider audience, not just you guys) to the fact there is support for sass compiling somewhere in the depths of KrakenJs.

However, I find myself confused about how this actually works, I assumed it would allow me to (in development mode) free me from having to open a second terminal and run grunt build (or modify grunt to include a watch task). 
- I've read through the source code, I vaguely understand that the sass and less module exports (is that the right phrase?) are middleware, I think. Does this mean they should execute before hitting the controller?
- I've installed node-sass (yay no more ruby!)
- I've pointed the config to my sass files.

The problem is that I assumed it would give me usable css files either:
- on the fly. no files are created, i simply refer to /styles/screen.sass in my html and kraken redirects this via middleware to the node-sass compiler?
- generates the css files in .build/styles ?

I don't think it's doing either of these, could you please advise me on how this works? 

edit: I should probably upload my project to github so you can see the horrible mistakes I'm making.

**Comment by jeffharrell** [comment]
Your assumption is right there's no grunt task needed. Instead you can simply reload.

I'm not in a position to give the code a shot, but the changes you made coupled with Erik's recommended config should register a sass compiler against `.css` files. Make sure you're referencing the `.css` file in your template (it looks like you're referencing `.sass`.

The compiler works on the fly until you start the app in with `NODE_ENV=production` at which point it will then start looking for precompiled files in `.build`. You'll want to make sure there's a grunt task for this that's similar to the LESS task already in there.

**Comment by airtonix** [comment]
@jeffharrell Oh so my html link tags need to point at .css files like normal. Do the sass files also have to be .css? or can I leave them as .sass?

**Comment by airtonix** [comment]
you know thinking about this, and the desire of your team to stay out of the way of choices developers would like to make, perhaps it would be better to have a middleware that simply runs grunt tasks with matching names.

so if I have : 

```
# config/middleware-development.json
{
    "middleware": {
        ...
        "grunt-tasks":[
            "clean:dev",
            "sass:dev",
            "lint:dev",
            "etc"
        ],
       ...
    }
}
```

Tell me if this is a crazy idea?

**Comment by jasisk** [comment]
@airtonix

> Oh so my html link tags need to point at .css files like normal.

That's correct (you can see exactly that in the [main layout](../../generator-kraken/blob/master/app/templates/public/templates/layouts/_master.dust#L6) of the yeoman generator).

> Do the sass files also have to be .css? or can I leave them as .sass?

With the sass compiler, css requests currently map to `.scss` files. So, a request like the following:

``` html
<link href="css/main.css" media="all" rel="stylesheet" type="text/css">
```

Would map to `public/css/main.scss` (by default).

**Comment by totherik** [comment]
Hey @airtonix, IIRC I tried that a looong time ago and I couldn't reliably block the request until the grunt task was complete. `devtools` does on-the-fly compiling per requested file. That way you can request js, css, templates, and other resources just as you would in non-dev mode, but any changes you make to the source are reflected immediately upon page refresh/request. If you ran the grunt tasks as described you'd build _all_ the files per request, which is less-than-optimal (assuming a single rendered page initiates n requests for resources.)

**Comment by airtonix** [comment]
@jasisk so is this documented somewhere? I can't find the string `scss` anywhere in the krakenjs source except in kraken devtools where the middleware is created.

I want to use the sass style syntax, can i just do : 

```
# config/middleware.json

{
    "middleware": {
        "session": {
            "module": "memory",
            "secret": "random-words"
        },
        "compiler": {
            "sass": {
                "syntax": "sass",
                "files": "public/sass/**/!(_).sass"
            },
            "dust": "templates",
            "default": ""
        }
    }
}
```

What do you guys think about the idea to simple defer development time pre request compiler tasks to what's in a gruntfile ?

You wouldn't have to deal with supporting various compile time middleware, instead defer it to a workflow many people are already familiar with (grunt)

**Comment by airtonix** [comment]
oh right I see, https://github.com/paypal/kraken-devtools/blob/master/index.js#L277

**Comment by jasisk** [comment]
> oh right I see, https://github.com/paypal/kraken-devtools/blob/master/index.js#L277

Bingo. `compiler`, in this case, is [this function](../../kraken-devtools/blob/master/index.js#L83) which is named `scss`.

Writing (or—in this case—using) another compiler falls out of what has been the typical use-case for us so it's presently pretty light on documentation. We're working on filling in some of those gaps right now.

> What do you guys think about the idea to simple defer development time pre request compiler tasks to what's in a gruntfile ?

Check out [Erik's comment](../../kraken-js/pull/25#issuecomment-29265749) above.

**Comment by airtonix** [comment]
@jasisk Ah ok. looks like i missed that (commented with an existing page without refreshing)

@totherik I'm confident you can make something happen that helps reduce the code you need to maintain. If i can come up with a prototype i'll do a pull request.

**Pull request merged**
